#!/bin/sh
set -eu

output=""
url=""
while [ "$#" -gt 0 ]; do
	case "$1" in
	-o)
		[ "$#" -ge 2 ] || exit 2
		output=$2
		shift 2
		;;
	-*) shift ;;
	*)
		url=$1
		shift
		;;
	esac
done

[ -n "$url" ] || exit 2
case "$url" in
*/releases/latest)
	[ -z "$output" ] || exit 2
	printf '%s\n' '{"tag_name":"v0.0.0"}'
	;;
*/checksums.txt)
	[ -n "$output" ] || exit 2
	cp "${INSTALL_TEST_CHECKSUMS:-$INSTALL_TEST_FIXTURES/checksums.txt}" "$output"
	;;
*/axilio_*_linux_amd64.tar.gz)
	[ -n "$output" ] || exit 2
	[ -f "$INSTALL_TEST_FIXTURES/${url##*/}" ] || exit 22
	cp "$INSTALL_TEST_FIXTURES/${url##*/}" "$output"
	;;
*)
	printf 'unexpected test URL: %s\n' "$url" >&2
	exit 22
	;;
esac
