package cmd

import (
	_ "embed"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/axilioai/cli/internal/exit"
	"github.com/spf13/cobra"
)

//go:embed agentskill.md
var agentSkillBody string

// skillDescription is the one-line summary in each agent's frontmatter.
const skillDescription = "Drive real Axilio phones from the axilio CLI (observe/find/tap/type), then write the equivalent SDK script in Python or Go."

const (
	claudeFrontmatter = "---\nname: axilio-phone-control\ndescription: " + skillDescription + "\n---\n\n"
	cursorFrontmatter = "---\ndescription: " + skillDescription + "\nalwaysApply: false\n---\n\n"
)

// skillStamp records which CLI version wrote a skill, and how to refresh it. The
// written file is a snapshot: `axilio upgrade` updates the binary but never the
// skills already on disk, so without a stamp a skill written months ago is
// indistinguishable from a current one — and the surface it documents moves.
func skillStamp(agent string) string {
	return fmt.Sprintf(
		"<!-- axilio skill %s — written by `axilio init --agent %s`.\n"+
			"     Refresh after `axilio upgrade`: `axilio init --agent %s --force` -->\n\n",
		Version, agent, agent,
	)
}

// AGENTS.md is a shared file, so the codex path appends a marked block rather
// than clobbering whatever the user already has.
const (
	agentsMarkerBegin = "<!-- axilio:begin (generated by `axilio init --agent codex`) -->"
	agentsMarkerEnd   = "<!-- axilio:end -->"
)

func initCmd() *cobra.Command {
	var agent string
	var force bool
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Drop an agent skill into this repo so a coding agent can drive phones via the CLI.",
		Long: "Write an instruction file that teaches your coding agent to drive a phone " +
			"through the axilio CLI and then hand back a runnable SDK script. The agent " +
			"asks whether you want Python or Go.\n\n" +
			"  --agent claude  ->  .claude/skills/axilio/SKILL.md\n" +
			"  --agent codex   ->  AGENTS.md (appended, never clobbered)\n" +
			"  --agent cursor  ->  .cursor/rules/axilio.mdc",
		RunE: func(_ *cobra.Command, _ []string) error {
			return runInit(agent, force)
		},
	}
	cmd.Flags().StringVar(&agent, "agent", "", "Target agent: claude | codex | cursor")
	cmd.Flags().BoolVar(&force, "force", false, "Overwrite/refresh an existing skill")
	return cmd
}

func runInit(agent string, force bool) error {
	switch strings.ToLower(strings.TrimSpace(agent)) {
	case "claude":
		return writeSkillFile(filepath.Join(".claude", "skills", "axilio", "SKILL.md"), claudeFrontmatter+skillStamp("claude")+agentSkillBody, force)
	case "cursor":
		return writeSkillFile(filepath.Join(".cursor", "rules", "axilio.mdc"), cursorFrontmatter+skillStamp("cursor")+agentSkillBody, force)
	case "codex":
		return writeAgentsMD(force)
	default:
		return exit.Usagef("choose an agent with --agent: claude, codex, or cursor")
	}
}

// writeSkillFile writes a dedicated, axilio-owned file (safe to overwrite with
// --force), creating parent directories as needed.
func writeSkillFile(path, content string, force bool) error {
	if _, err := os.Stat(path); err == nil && !force {
		return exit.Usagef("%s already exists; pass --force to overwrite", path)
	}
	if dir := filepath.Dir(path); dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return err
	}
	reportInit(path)
	return nil
}

// writeAgentsMD appends a marker-delimited Axilio section to AGENTS.md, creating
// it if absent. It never clobbers other content; a re-run refreshes only the
// marked block (with --force) rather than duplicating it.
//
// The stamp goes inside the block, not in the markers: the markers are matched
// with strings.Index to find an existing section, so a version in them would stop
// a newer CLI from recognising (and refreshing) a block an older one wrote.
func writeAgentsMD(force bool) error {
	const path = "AGENTS.md"
	block := agentsMarkerBegin + "\n\n" + skillStamp("codex") + agentSkillBody + "\n" + agentsMarkerEnd + "\n"

	existing, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		if werr := os.WriteFile(path, []byte(block), 0o644); werr != nil {
			return werr
		}
		reportInit(path)
		return nil
	}
	if err != nil {
		return err
	}

	s := string(existing)
	if b := strings.Index(s, agentsMarkerBegin); b != -1 {
		if !force {
			return exit.Usagef("AGENTS.md already has the Axilio section; pass --force to refresh it")
		}
		e := strings.Index(s, agentsMarkerEnd)
		if e == -1 || e < b {
			return exit.Usagef("AGENTS.md has a malformed Axilio section; fix or remove it, then re-run")
		}
		s = s[:b] + strings.TrimRight(block, "\n") + s[e+len(agentsMarkerEnd):]
	} else {
		sep := "\n"
		if !strings.HasSuffix(s, "\n") {
			sep = "\n\n"
		}
		s += sep + block
	}
	if werr := os.WriteFile(path, []byte(s), 0o644); werr != nil {
		return werr
	}
	reportInit(path)
	return nil
}

func reportInit(path string) {
	p := printer()
	p.Success("Wrote the Axilio agent skill to %s", path)
	p.Note("  Now tell your agent: \"drive my phone with the axilio CLI and hand me the SDK script.\"")
}
