package cmd

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/axilioai/cli/internal/exit"
	"github.com/axilioai/cli/internal/oauth"
	"github.com/axilioai/cli/internal/util"
	"github.com/spf13/cobra"
	"golang.org/x/term"
)

// skillURL is where the canonical agent skill markdown is hosted (AXI-1527).
// It's the same content the dashboard's "Get Agent Prompt" button fetches —
// centralizing it means an edit lands in one place (the backend's /skill
// route) instead of needing a matching commit here and in the dashboard.
func skillURL() string {
	_, host := resolvedCreds()
	return sdkBaseURL(util.FirstNonEmpty(host, defaultAPIHost)) + "/skill"
}

// fetchSkillBody downloads the current agent skill markdown. This makes
// `init` require network, but it already did: the sign-in check a few lines
// later needs it too, and a skill fetched fresh can never be the stale-embed
// problem skillStamp exists to warn about.
func fetchSkillBody(ctx context.Context) (string, error) {
	url := skillURL()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return "", err
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("could not reach %s: %w", url, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("fetching agent skill from %s: unexpected status %d", url, resp.StatusCode)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}
	return string(body), nil
}

// skillDescription is the one-line summary in each agent's frontmatter.
const skillDescription = "Drive real Axilio phones from the axilio CLI (observe/find/tap/type), then write the equivalent SDK script in Python or Go."

const (
	claudeFrontmatter = "---\nname: axilio-phone-control\ndescription: " + skillDescription + "\n---\n\n"
	cursorFrontmatter = "---\ndescription: " + skillDescription + "\nalwaysApply: false\n---\n\n"
)

// skillStamp records which CLI version wrote a skill, and how to refresh it. The
// written file is a snapshot: `axilio upgrade` updates the binary but never the
// skills already on disk, so without a stamp a skill written months ago is
// indistinguishable from a current one — and the surface it documents moves.
func skillStamp(agent string) string {
	return fmt.Sprintf(
		"<!-- axilio skill %s — written by `axilio init --agent %s`.\n"+
			"     Refresh after `axilio upgrade`: `axilio init --agent %s --force` -->\n\n",
		Version, agent, agent,
	)
}

// AGENTS.md is a shared file, so the codex path appends a marked block rather
// than clobbering whatever the user already has.
const (
	agentsMarkerBegin = "<!-- axilio:begin (generated by `axilio init --agent codex`) -->"
	agentsMarkerEnd   = "<!-- axilio:end -->"
)

func initCmd() *cobra.Command {
	var agent string
	var force bool
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Drop an agent skill into this repo so a coding agent can drive phones via the CLI.",
		Long: "Write an instruction file that teaches your coding agent to drive a phone " +
			"through the axilio CLI and then hand back a runnable SDK script. The agent " +
			"asks whether you want Python or Go.\n\n" +
			"Bare `axilio init` detects which agents this repo uses (.claude/, AGENTS.md, " +
			".cursor/) and writes a skill for each; on a terminal with nothing detected it " +
			"asks. --agent picks one explicitly:\n\n" +
			"  --agent claude  ->  .claude/skills/axilio/SKILL.md\n" +
			"  --agent codex   ->  AGENTS.md (appended, never clobbered)\n" +
			"  --agent cursor  ->  .cursor/rules/axilio.mdc\n\n" +
			"Auto-detected targets that already contain the skill are skipped. An " +
			"explicit target that already exists is an error unless --force is set; " +
			"for AGENTS.md, --force replaces only the marked Axilio block. Without " +
			"markers, interactive mode asks which agent to configure, while JSON, " +
			"quiet, or redirected use requires --agent.\n\n" +
			"It finishes with a sign-in check: browser login is the one step an agent " +
			"can't do itself, so init surfaces it while a human is likely at the keyboard.",
		Example: `  axilio init
  axilio init --agent codex
  axilio init --agent claude --force`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			return runInit(cmd.Context(), agent, force)
		},
	}
	cmd.Flags().StringVar(&agent, "agent", "", "Target claude, codex, or cursor; omit to detect repository markers")
	cmd.Flags().BoolVar(&force, "force", false, "Refresh an existing skill; only the marked Axilio AGENTS.md block is replaced")
	return cmd
}

func runInit(ctx context.Context, agent string, force bool) error {
	targets, explicit, err := initTargets(agent)
	if err != nil {
		return err
	}
	body, err := fetchSkillBody(ctx)
	if err != nil {
		return fmt.Errorf("fetching the agent skill: %w", err)
	}
	written := []string{}
	skipped := []string{}
	for _, t := range targets {
		// Auto-detected targets that already carry the skill are skipped with a
		// note; only an explicit --agent hard-errors, since then the user named
		// exactly one file and silence about it would be a lie.
		if !explicit && !force && skillPresent(t) {
			printer().Note("  %s already has the skill; refresh with `axilio init --agent %s --force`.", skillTargetPath(t), t)
			skipped = append(skipped, skillTargetPath(t))
			continue
		}
		if err := writeAgentTarget(t, body, force); err != nil {
			return err
		}
		written = append(written, skillTargetPath(t))
	}
	// The human chrome (per-file Success lines, sign-in check) already went to
	// stderr; the JSON result carries what was written and what was left alone.
	printer().Emit(map[string]any{"written": written, "skipped": skipped}, func() {})
	initNextSteps(ctx)
	return nil
}

func writeAgentTarget(agent, body string, force bool) error {
	switch agent {
	case "claude":
		return writeSkillFile(filepath.Join(".claude", "skills", "axilio", "SKILL.md"), claudeFrontmatter+skillStamp("claude")+body, force)
	case "cursor":
		return writeSkillFile(filepath.Join(".cursor", "rules", "axilio.mdc"), cursorFrontmatter+skillStamp("cursor")+body, force)
	default:
		return writeAgentsMD(body, force)
	}
}

// skillTargetPath is where each agent's skill lands, for messages and existence
// checks.
func skillTargetPath(agent string) string {
	switch agent {
	case "claude":
		return filepath.Join(".claude", "skills", "axilio", "SKILL.md")
	case "cursor":
		return filepath.Join(".cursor", "rules", "axilio.mdc")
	default:
		return "AGENTS.md"
	}
}

// skillPresent reports whether the target already carries the skill. For codex
// that means the marked block inside AGENTS.md, not the file itself — AGENTS.md
// is shared, and one without our block still wants the append.
func skillPresent(agent string) bool {
	if agent == "codex" {
		b, err := os.ReadFile("AGENTS.md")
		return err == nil && strings.Contains(string(b), agentsMarkerBegin)
	}
	_, err := os.Stat(skillTargetPath(agent))
	return err == nil
}

// initTargets resolves which agents to write for: the --agent flag wins, then
// repo markers, then (on a terminal) an interactive choice. explicit reports
// whether the user named the agent, which sharpens the already-exists handling.
func initTargets(agent string) (targets []string, explicit bool, err error) {
	a := strings.ToLower(strings.TrimSpace(agent))
	if a != "" {
		if a != "claude" && a != "codex" && a != "cursor" {
			return nil, true, exit.Usagef("choose an agent with --agent: claude, codex, or cursor")
		}
		return []string{a}, true, nil
	}
	var detected []string
	if st, err := os.Stat(".claude"); err == nil && st.IsDir() {
		detected = append(detected, "claude")
	}
	if _, err := os.Stat("AGENTS.md"); err == nil {
		detected = append(detected, "codex")
	}
	if st, err := os.Stat(".cursor"); err == nil && st.IsDir() {
		detected = append(detected, "cursor")
	}
	if len(detected) > 0 {
		return detected, false, nil
	}
	if choice, ok := promptAgentChoice(); ok {
		return choice, false, nil
	}
	return nil, false, exit.Usagef("no agent markers found (.claude/, AGENTS.md, .cursor/); choose one with --agent: claude, codex, or cursor")
}

// promptAgentChoice asks which agent to set up when the repo carries no markers.
// Only on a real terminal outside quiet/JSON mode — the non-interactive contract
// is a usage error, never a hang on stdin.
func promptAgentChoice() ([]string, bool) {
	if flagQuiet || flagOutput == "json" || !term.IsTerminal(int(os.Stdin.Fd())) {
		return nil, false
	}
	fmt.Fprintln(os.Stderr, "Which agent runs in this repo?")
	fmt.Fprintln(os.Stderr, "  1) claude  (.claude/skills/)")
	fmt.Fprintln(os.Stderr, "  2) codex   (AGENTS.md)")
	fmt.Fprintln(os.Stderr, "  3) cursor  (.cursor/rules/)")
	fmt.Fprintln(os.Stderr, "  4) all three")
	fmt.Fprint(os.Stderr, "Choose [1-4]: ")
	line, _ := bufio.NewReader(os.Stdin).ReadString('\n')
	switch strings.ToLower(strings.TrimSpace(line)) {
	case "1", "claude":
		return []string{"claude"}, true
	case "2", "codex":
		return []string{"codex"}, true
	case "3", "cursor":
		return []string{"cursor"}, true
	case "4", "all":
		return []string{"claude", "codex", "cursor"}, true
	}
	return nil, false
}

// agentFirstPrompt is the copy-pasteable first thing to say to an agent once
// the skill is in place — a concrete task plus the durable deliverable.
const agentFirstPrompt = `Use the axilio CLI to take a phone, open the browser, search for something — then hand me the SDK script.`

// initNextSteps closes the loop after the skill lands: confirm sign-in (browser
// login is the one step an agent can't do itself, so surface it while a human
// is likely at the keyboard), then hand over the first prompt for the agent.
func initNextSteps(ctx context.Context) {
	p := printer()
	key, host := resolvedCreds()
	apiHost := util.FirstNonEmpty(host, defaultAPIHost)
	switch {
	case key != "":
		p.Success("Signed in to %s (API key)", apiHost)
	case oauthSignedIn(ctx, apiHost):
		tok, _ := oauth.Load()
		if org := sessionOrgLabel(tok); org != "" {
			p.Success("Signed in to %s (org %s)", apiHost, org)
		} else {
			p.Success("Signed in to %s", apiHost)
		}
	case term.IsTerminal(int(os.Stdin.Fd())) && p.Confirm("You're not signed in — open the browser to log in now?"):
		if err := loginWithBrowser(ctx); err != nil {
			p.Note("Login didn't complete (%v); run `axilio login` when ready.", err)
		}
	default:
		p.Note("Not signed in. A human must run `axilio login` (browser), or set AXILIO_API_KEY.")
	}
	p.Note("\nNow tell your agent:\n  %q", agentFirstPrompt)
}

// oauthSignedIn reports whether a usable OAuth session exists for apiHost,
// refreshing (and pruning a dead session) as a side effect when needed.
func oauthSignedIn(ctx context.Context, apiHost string) bool {
	_, err := oauth.ValidAccessToken(ctx, apiHost)
	return err == nil
}

// writeSkillFile writes a dedicated, axilio-owned file (safe to overwrite with
// --force), creating parent directories as needed.
func writeSkillFile(path, content string, force bool) error {
	if _, err := os.Stat(path); err == nil && !force {
		return exit.Usagef("%s already exists; pass --force to overwrite", path)
	}
	if dir := filepath.Dir(path); dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return err
	}
	reportInit(path)
	return nil
}

// writeAgentsMD appends a marker-delimited Axilio section to AGENTS.md, creating
// it if absent. It never clobbers other content; a re-run refreshes only the
// marked block (with --force) rather than duplicating it.
//
// The stamp goes inside the block, not in the markers: the markers are matched
// with strings.Index to find an existing section, so a version in them would stop
// a newer CLI from recognizing (and refreshing) a block an older one wrote.
func writeAgentsMD(body string, force bool) error {
	const path = "AGENTS.md"
	block := agentsMarkerBegin + "\n\n" + skillStamp("codex") + body + "\n" + agentsMarkerEnd + "\n"

	existing, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		if werr := os.WriteFile(path, []byte(block), 0o644); werr != nil {
			return werr
		}
		reportInit(path)
		return nil
	}
	if err != nil {
		return err
	}

	s := string(existing)
	if b := strings.Index(s, agentsMarkerBegin); b != -1 {
		if !force {
			return exit.Usagef("AGENTS.md already has the Axilio section; pass --force to refresh it")
		}
		e := strings.Index(s, agentsMarkerEnd)
		if e == -1 || e < b {
			return exit.Usagef("AGENTS.md has a malformed Axilio section; fix or remove it, then re-run")
		}
		s = s[:b] + strings.TrimRight(block, "\n") + s[e+len(agentsMarkerEnd):]
	} else {
		sep := "\n"
		if !strings.HasSuffix(s, "\n") {
			sep = "\n\n"
		}
		s += sep + block
	}
	if werr := os.WriteFile(path, []byte(s), 0o644); werr != nil {
		return werr
	}
	reportInit(path)
	return nil
}

func reportInit(path string) {
	printer().Success("Wrote the Axilio agent skill to %s", path)
}
